### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by jonasmalacofilho** [nicootto/epson-l4160-ink-waste-resetter#1]
Hey @nicootto ,

I may need to adapt this to support the L3250 model.  How did you find the necessary OIDs for the L4160?

Also, I don't really know how SNMP works, but isn't it a bit weird that simply getting these values resets the counter?

Thanks!

**Comment by jonasmalacofilho** [comment]
P.S. Feel free to reply by email.  My email address (and twitter handle) is in my profile.

**Comment by nicootto** [comment]
Hi @jonasmalacofilho! When I did this I didn't found too much documentation from Epson. After long time digging the web without much success, I ended up buying a license from [https://www.wic.support/](https://www.wic.support/). I captured with Wireshark the packages sent to the printer when the software resets the counter. Then, I checked what happened if I send those same packages, and the counter effectively was reset. That is all the script does. 

If you find how to do the same with L3250 please open a PR to add it to the repo, so you can save someone else money :) Or let me know and I can link a repo of yours on the Readme.

Cheers,

**Comment by jonasmalacofilho** [comment]
Will do, and thanks for the info!

**Comment by changbowen** [comment]
Wow I did not expect Wireshark to be a part of this... Amazing!
